// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { ParcelTerrain, ParcelTerrainTableId } from "./tables/ParcelTerrain.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { PlayerPosition, PlayerPositionTableId } from "./tables/PlayerPosition.sol";
import { PCClass, PCClassData, PCClassTableId } from "./tables/PCClass.sol";
import { PCInstance, PCInstanceData, PCInstanceTableId } from "./tables/PCInstance.sol";
import { AttackClass, AttackClassData, AttackClassTableId } from "./tables/AttackClass.sol";
import { CommandedBy, CommandedByTableId } from "./tables/CommandedBy.sol";
import { BattleWith, BattleWithTableId } from "./tables/BattleWith.sol";
import { SiegedBy, SiegedByTableId } from "./tables/SiegedBy.sol";
