// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ParcelType {
  CUSTOMIZED,
  NONE,
  LEFT,
  UP,
  RIGHT,
  DOWN,
  LEFTUP,
  RIGHTUP,
  RIGHTDOWN,
  LEFTDOWN
}

enum TerrainType {
  NONE,
  TREE,
  GRASS,
  FLOWER,
  CONSOLE
}

enum AttackType {
  NORMAL,
  PARALYSIS
}
