// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum ParcelType {
  CUSTOMIZED,
  NONE,
  LEFT,
  UP,
  RIGHT,
  DOWN,
  LEFTUP,
  RIGHTUP,
  RIGHTDOWN,
  LEFTDOWN,
  NONE1,
  LEFT1,
  UP1,
  RIGHT1,
  DOWN1,
  LEFTUP1,
  RIGHTUP1,
  RIGHTDOWN1,
  LEFTDOWN1
}

enum TerrainType {
  NONE,
  TREE,
  GRASS,
  FLOWER,
  WATER,
  GRAVEL,
  CONSOLE
}

enum AttackType {
  NORMAL,
  PARALYSIS
}
