// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBattleSystem {
  function netherscape_BattleSystem_attack(bytes32 attacker_pcID, bytes32 target_pcID, bytes32 attackID) external;
}
