// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBattleInitSystem {
  function netherscape_battleInit_battleInit(bytes32 attacker, bytes32 defender) external;
}
