// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICrawlSystem {
  function netherscape_CrawlSystem_crawl(uint16 x, uint16 y) external;

  function netherscape_CrawlSystem_spawn() external;

  function netherscape_CrawlSystem_respawn() external;

  function netherscape_CrawlSystem_logout() external;
}
