// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ParcelType } from "./../Types.sol";

interface IMapSystem {
  function netherscape_MapSystem_initMapConfig(uint8[32][32] memory map) external;

  function netherscape_MapSystem_submitParcelTemplate(ParcelType parcelType, bytes memory terrainMap) external;
}
