// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { AttackClassData } from "./../tables/AttackClass.sol";
import { PCClassData } from "./../tables/PCClass.sol";

interface IPCSystem {
  function netherscape_PCSystem_createNewAttackClass(
    bytes32 attackClassID,
    AttackClassData memory attackClassData
  ) external;

  function netherscape_PCSystem_createNewPCClass(bytes32 pcClassID, PCClassData memory pcClassData) external;

  function netherscape_PCSystem_spawnPC(bytes32 PCClassID, bytes32 player) external;

  function netherscape_PCSystem_askToJoin() external;
}
