// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISiegeSystem {
  function netherscape_SiegeSystem_siege() external;

  function netherscape_SiegeSystem_unsiege() external;
}
