// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { ICrawlSystem } from "./ICrawlSystem.sol";
import { IMapSystem } from "./IMapSystem.sol";
import { IPCSystem } from "./IPCSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, ICrawlSystem, IMapSystem, IPCSystem {

}
